Added MP3Header#duration
ahwatts/mp3file pull request #1
Opened 2018-05-17 08:44 UTC by njh

A small change to add a MP3Header#duration method

2018-05-17 08:44 UTC, njh commented
Background is that I am working on a ruby script to convert an MP3 file into an HLS stream:
https://github.com/njh/mp3-to-hls

Being able to easily get the duration of a frame would make much code simpler.

2018-05-17 08:45 UTC, njh commented
ps. thank you for writing this gem!

2018-05-17 14:09 UTC, ahwatts requested changes
Thanks for the PR!

In general, it looks good to me. Just a little clarity change to the test, and I'll merge it.

2018-05-17 14:09 UTC, ahwatts commented on spec/mp3file/mp3_header_spec.rb
> +        expect(h.duration).to eq(duration)
This is a floating-point comparison, so the `be_within` matcher might be more appropriate here.

Given that the sample counts are on the order of 100 samples / frame, and the sample rates are on the order of 10 kHz, we would expect the durations to be on the order of (100 / 10000) = 1e-2 sec.

Could you change the expected durations to be e.g. (for a 44.1kHz MPEG-1 Layer III) `1152.0 / 44100.0` to make it more obvious where they come from, and then expect the code's answer to `be_within(1e-5).of(duration)`, ensuring that we're within 0.1% of the correct duration.

2018-05-18 13:56 UTC, ahwatts approved these changes

2018-05-18 13:57 UTC, merged

2018-05-18 14:01 UTC, ahwatts commented
I cut a new release with these changes: v1.3.0

2018-05-18 23:42 UTC, njh commented
That is awesome, thank you very much!